
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

/**
 *
 * @author lzamo
 */
public class AgregarEliminar extends javax.swing.JFrame {
    private static asistenciaColegio asistenciaColegioAux;
    /**
     * Creates new form AgregarEliminar
     */
    public AgregarEliminar(asistenciaColegio asistenciaColegioAux) {
        initComponents();
        this.asistenciaColegioAux = asistenciaColegioAux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        asistencia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        eliminarCurso = new javax.swing.JButton();
        textoParaBuscarCurso = new javax.swing.JTextField();
        agregarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asistencia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        asistencia.setText("Agregar - Eliminar curso");
        background.add(asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 270, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(volver)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(89, 89, 89))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 470));

        eliminarCurso.setText("Eliminar Curso");
        eliminarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarCursoMouseClicked(evt);
            }
        });
        eliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCursoActionPerformed(evt);
            }
        });
        background.add(eliminarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, -1));

        textoParaBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoParaBuscarCursoActionPerformed(evt);
            }
        });
        background.add(textoParaBuscarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 150, 40));

        agregarCurso.setText("Agregar Curso");
        agregarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarCursoMouseClicked(evt);
            }
        });
        agregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCursoActionPerformed(evt);
            }
        });
        background.add(agregarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        Menu irMenu = null;
        try {
            irMenu = new Menu();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
        irMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void agregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCursoActionPerformed
        String nombreCurso = textoParaBuscarCurso.getText().trim();

        if (!nombreCurso.isEmpty()) {
            try {
                if (agregarCurso(nombreCurso)) {
                    JOptionPane.showMessageDialog(this, "Curso agregado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar el curso", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (CursoYaExisteException ex) {
                Logger.getLogger(AgregarEliminar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de curso válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarCursoActionPerformed

    private void eliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCursoActionPerformed
        String nombreCurso = textoParaBuscarCurso.getText().trim();

        if (!nombreCurso.isEmpty()) {
            try {
                if (eliminarCurso(nombreCurso)) {
                    JOptionPane.showMessageDialog(this, "Curso eliminado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el curso", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (CursoNoEncontradoException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de curso válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarCursoActionPerformed

    private void eliminarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarCursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCursoMouseClicked

    private void textoParaBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoParaBuscarCursoActionPerformed
        String nombreCurso = textoParaBuscarCurso.getText().trim();

        if (!nombreCurso.isEmpty()) {
            try {
                if (agregarCurso(nombreCurso)) {
                    JOptionPane.showMessageDialog(this, "Curso agregado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar el curso", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (CursoYaExisteException ex) {
                Logger.getLogger(AgregarEliminar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de curso válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textoParaBuscarCursoActionPerformed
    private boolean agregarCurso(String nombreCurso) throws CursoYaExisteException {
        // Verificar si el curso ya existe antes de agregarlo
        if (asistenciaColegioAux.cursoExiste(nombreCurso)) {
            throw new CursoYaExisteException("El curso ya existe.");
        }
        // Si el curso no existe, agregarlo
        asistenciaColegioAux.agregarCurso(nombreCurso);
        return true;
    }


    

    private boolean eliminarCurso(String nombreCurso) throws CursoNoEncontradoException {
        // Verificar si el curso existe antes de intentar eliminarlo
        if (!asistenciaColegioAux.cursoExiste(nombreCurso)) {
            throw new CursoNoEncontradoException("El curso no existe.");
        }
        // Si el curso existe, proceder con la eliminación
        asistenciaColegioAux.eliminarCurso(nombreCurso);
        return true;
    }

    
    private void agregarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarCursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarCursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEliminar(asistenciaColegioAux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCurso;
    private javax.swing.JLabel asistencia;
    private javax.swing.JPanel background;
    private javax.swing.JButton eliminarCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoParaBuscarCurso;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
