
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

/**
 *
 * @author lzamo
 */
public class Menu extends javax.swing.JFrame {
    
    private static asistenciaColegio asistenciaColegioAux;

    
    /**
     * Creates new form Menu
     * @throws java.io.FileNotFoundException
     */
    public Menu() throws FileNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        asistencia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregarEliminarCurso = new javax.swing.JButton();
        agregarAlumno = new javax.swing.JButton();
        pasarAsistencia = new javax.swing.JButton();
        mostrarCursos = new javax.swing.JButton();
        mostrarAsistencia = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        generarReporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asistencia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        asistencia.setText("Aplicación de Control de Asistencia Escolar");
        background.add(asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 470, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        agregarEliminarCurso.setText("Agregar/Eliminar curso");
        agregarEliminarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarEliminarCursoMouseClicked(evt);
            }
        });
        agregarEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEliminarCursoActionPerformed(evt);
            }
        });

        agregarAlumno.setText("Agregar alumno");
        agregarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarAlumnoMouseClicked(evt);
            }
        });
        agregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlumnoActionPerformed(evt);
            }
        });

        pasarAsistencia.setText("Pasar asistencia ");
        pasarAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasarAsistenciaMouseClicked(evt);
            }
        });

        mostrarCursos.setText("Mostrar  cursos");
        mostrarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarCursosMouseClicked(evt);
            }
        });
        mostrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCursosActionPerformed(evt);
            }
        });

        mostrarAsistencia.setText("Mostrar asistencia");
        mostrarAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarAsistenciaMouseClicked(evt);
            }
        });
        mostrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAsistenciaActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        generarReporte.setText("Generar Reporte");
        generarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(salir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostrarAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostrarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(agregarAlumno)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(agregarEliminarCurso)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(generarReporte)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pasarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(generarReporte)
                .addGap(31, 31, 31)
                .addComponent(agregarEliminarCurso)
                .addGap(32, 32, 32)
                .addComponent(agregarAlumno)
                .addGap(33, 33, 33)
                .addComponent(pasarAsistencia)
                .addGap(40, 40, 40)
                .addComponent(mostrarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(mostrarAsistencia)
                .addGap(53, 53, 53)
                .addComponent(salir)
                .addGap(41, 41, 41))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 450));

        jTextPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextPane1.setText("El menú se presenta de la siguiente manera.\n\n1. Agregar y eliminar cursos: Permite agregar o eliminar cursos.\n2. Agregar/Modificar/Eliminar Alumno: Agrega alumnos a cursos existentes especificando su nombre, apellido y rut. También permite eliminar alumno utilizando los mismos datos. Adicionalmente permite modificar los datos del alumno, utilizando sus mismos datos.\n3. Pasar asistencia en un curso: Registra la asistencia de los alumnos en un curso en una fecha específica.\n4. Mostrar todos los cursos y alumnos de ese curso: Consulta la información de todos los cursos registrados y permite visualizar los alumnos de un curso en específico.\n5. Mostrar asistencia de un curso: Consulta la asistencia de un curso en una fecha determinada.\n6. Generar reporte: Recibe una fecha en específico y genera un reporte para ese día, si por ejemplo se pasa asistencia solamente para un curso en una fecha específica, se asume que todos los cursos en los que no se pasó asistencia, todos sus alumnos están ausentes.\n7. Salir: Cierra la aplicación y guarda los datos.\n");
        jScrollPane2.setViewportView(jTextPane1);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 580, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarAsistenciaActionPerformed

    private void mostrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarCursosActionPerformed

    private void mostrarCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarCursosMouseClicked
        MostrarCursos irAMostrarCursos= new MostrarCursos(asistenciaColegioAux);
        irAMostrarCursos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mostrarCursosMouseClicked

    private void agregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarAlumnoActionPerformed

    private void agregarEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEliminarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEliminarCursoActionPerformed

    private void agregarEliminarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarEliminarCursoMouseClicked
        AgregarEliminar irAgregarEliminar= new AgregarEliminar(asistenciaColegioAux);
        irAgregarEliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarEliminarCursoMouseClicked

    private void agregarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarAlumnoMouseClicked
        AgregarAlumno irAgregarAlumno= new AgregarAlumno(asistenciaColegioAux);
        irAgregarAlumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarAlumnoMouseClicked

    private void pasarAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasarAsistenciaMouseClicked
        PasarAsistencia irPasarAsistencia= new PasarAsistencia(asistenciaColegioAux);
        irPasarAsistencia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pasarAsistenciaMouseClicked

    private void mostrarAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarAsistenciaMouseClicked
        MostrarAsistencia irMostrarAsistencia= new MostrarAsistencia(asistenciaColegioAux);
        irMostrarAsistencia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mostrarAsistenciaMouseClicked

    private void generarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarReporteMouseClicked

        GenerarReporte irGenerarReporte= new GenerarReporte(asistenciaColegioAux);
        irGenerarReporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generarReporteMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        try {
            // Llama a la función para guardar los datos antes de salir
            asistenciaColegioAux.guardarAlSalir();
            // Cierra la aplicación
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            asistenciaColegioAux = asistenciaColegio.getInstance();
            asistenciaColegioAux.inicializarDatos(); // Mueve la inicialización aquí
            new Menu().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlumno;
    private javax.swing.JButton agregarEliminarCurso;
    private javax.swing.JLabel asistencia;
    private javax.swing.JPanel background;
    private javax.swing.JButton generarReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton mostrarAsistencia;
    private javax.swing.JButton mostrarCursos;
    private javax.swing.JButton pasarAsistencia;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
