
import java.io.FileNotFoundException;
import java.lang.System.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

/**
 *
 * @author lzamo
 */
public class ModificarDatos extends javax.swing.JFrame {
    private static asistenciaColegio asistenciaColegioAux;
    private static Alumnos alumnoAModificar;
    /**
     * Creates new form ModificarDatos
     */
    public ModificarDatos(asistenciaColegio asistenciaColegioAux,Alumnos alumnoAux) {
        
        initComponents();
        this.asistenciaColegioAux = asistenciaColegioAux;
        this.alumnoAModificar = alumnoAux;
        
        // Mostrar los datos actuales del alumno en los campos de texto
        textoRutAntiguo.setText(alumnoAux.getRut());
        textoNombreAntiguo.setText(alumnoAux.getNombre());
        textoApellidoAntiguo.setText(alumnoAux.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        textoNombreNuevo = new javax.swing.JTextField();
        textoApellidoNuevo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoRutNuevo = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        textoApellidoAntiguo = new javax.swing.JTextField();
        textoNombreAntiguo = new javax.swing.JTextField();
        textoRutAntiguo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(volver)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(95, 95, 95))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 470));

        textoNombreNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreNuevoActionPerformed(evt);
            }
        });
        background.add(textoNombreNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 200, -1));
        background.add(textoApellidoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 180, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Modificar datos Alumno");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 280, 50));

        jLabel2.setText("Rut");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 30, 20));

        jLabel3.setText("Nombre");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel4.setText("Apellido");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        textoRutNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRutNuevoActionPerformed(evt);
            }
        });
        background.add(textoRutNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 200, -1));

        Modificar.setText("Modificar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        background.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 90, -1));
        background.add(textoApellidoAntiguo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 180, -1));

        textoNombreAntiguo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreAntiguoActionPerformed(evt);
            }
        });
        background.add(textoNombreAntiguo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, -1));
        background.add(textoRutAntiguo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        AgregarAlumno irAgregarAlumno = null;
        irAgregarAlumno = new AgregarAlumno(asistenciaColegioAux);
        irAgregarAlumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void textoNombreNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreNuevoActionPerformed

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // Obtener los nuevos valores ingresados por el usuario
        String nuevoRut = textoRutNuevo.getText().trim();
        String nuevoNombre = textoNombreNuevo.getText().trim();
        String nuevoApellido = textoApellidoNuevo.getText().trim();
        
        // Actualizar los datos del alumno con los nuevos valores

        alumnoAModificar.setRut(nuevoRut);
        alumnoAModificar.setNombre(nuevoNombre);
        alumnoAModificar.setApellido(nuevoApellido);
        
        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Datos del alumno modificados con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ModificarActionPerformed

    private void textoNombreAntiguoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreAntiguoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreAntiguoActionPerformed

    private void textoRutNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRutNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRutNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatos(asistenciaColegioAux,alumnoAModificar).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoApellidoAntiguo;
    private javax.swing.JTextField textoApellidoNuevo;
    private javax.swing.JTextField textoNombreAntiguo;
    private javax.swing.JTextField textoNombreNuevo;
    private javax.swing.JTextField textoRutAntiguo;
    private javax.swing.JTextField textoRutNuevo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
